Make 'make check' more consistent across projects
packit/sandcastle pull request #130
Opened 2021-05-28 02:41 UTC by bcrocker15

Make 'make check' more consistent across projects

No changes really needed to be made to Makefile here.

In a standup meeting, we decided to add a reference to README.md
to CONTRIBUTING.md, as the information that normally appears in
CONTRIBUTING.md in our other subprojects appears in README.md here.

Minor language fixes to CONTRIBUTING.md.

Signed-off-by: Ben Crocker <bcrocker@redhat.com>

2021-05-31 08:53 UTC, TomasTomecek approved these changes
Thanks! good updates and the docs is now very well cleaned up

2021-05-31 12:41 UTC, mfocko approved these changes

2021-06-01 08:14 UTC, csomh requested changes
Please also update the Makefile so that the naming of the targets is in line with the naming we agreed on.
Would be nice if the same `CONTAINER_ENGINE` approach could be used as in other projects, instead of just running `docker`. I think, but you might need to check this, that this will still work, and tests will be able to communicate with the test cluster from a podman container.
Also the README will need to be updated to mention that running the tests requires podman or docker and adjust for the name-change of the target.

2021-06-02 10:43 UTC, csomh approved these changes
Thank you @bcrocker15! This is good to be merged.

Please squash the 2 commits into one before doing so.

2021-06-03 18:40 UTC, merged